// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeRedux.Data;

#nullable disable

namespace RecipeRedux.Migrations
{
    [DbContext(typeof(RecipeReduxContext))]
    [Migration("20240416031333_AddedEssentialIngredients")]
    partial class AddedEssentialIngredients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecipeRedux.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Category = "Essential Ingredients",
                            Name = "Salt"
                        },
                        new
                        {
                            IngredientId = 2,
                            Category = "Essential Ingredients",
                            Name = "Water"
                        },
                        new
                        {
                            IngredientId = 3,
                            Category = "Essential Ingredients",
                            Name = "Butter"
                        },
                        new
                        {
                            IngredientId = 4,
                            Category = "Essential Ingredients",
                            Name = "Milk"
                        },
                        new
                        {
                            IngredientId = 5,
                            Category = "Essential Ingredients",
                            Name = "Egg"
                        },
                        new
                        {
                            IngredientId = 6,
                            Category = "Essential Ingredients",
                            Name = "Garlic"
                        },
                        new
                        {
                            IngredientId = 7,
                            Category = "Essential Ingredients",
                            Name = "Onion"
                        },
                        new
                        {
                            IngredientId = 8,
                            Category = "Essential Ingredients",
                            Name = "Sugar"
                        },
                        new
                        {
                            IngredientId = 9,
                            Category = "Essential Ingredients",
                            Name = "Flour"
                        },
                        new
                        {
                            IngredientId = 10,
                            Category = "Essential Ingredients",
                            Name = "Olive Oil"
                        },
                        new
                        {
                            IngredientId = 11,
                            Category = "Essential Ingredients",
                            Name = "Garlic Powder"
                        },
                        new
                        {
                            IngredientId = 12,
                            Category = "Essential Ingredients",
                            Name = "White Rice"
                        },
                        new
                        {
                            IngredientId = 13,
                            Category = "Essential Ingredients",
                            Name = "Cinnamon"
                        },
                        new
                        {
                            IngredientId = 14,
                            Category = "Essential Ingredients",
                            Name = "Ketchup"
                        },
                        new
                        {
                            IngredientId = 15,
                            Category = "Essential Ingredients",
                            Name = "Soy Sauce"
                        },
                        new
                        {
                            IngredientId = 16,
                            Category = "Essential Ingredients",
                            Name = "Mayonnaise"
                        },
                        new
                        {
                            IngredientId = 17,
                            Category = "Essential Ingredients",
                            Name = "Vegetable Oil"
                        },
                        new
                        {
                            IngredientId = 18,
                            Category = "Essential Ingredients",
                            Name = "Bread"
                        },
                        new
                        {
                            IngredientId = 19,
                            Category = "Essential Ingredients",
                            Name = "Baking Powder"
                        },
                        new
                        {
                            IngredientId = 20,
                            Category = "Essential Ingredients",
                            Name = "Baking Soda"
                        },
                        new
                        {
                            IngredientId = 21,
                            Category = "Essential Ingredients",
                            Name = "Oregano"
                        },
                        new
                        {
                            IngredientId = 22,
                            Category = "Essential Ingredients",
                            Name = "Potato"
                        },
                        new
                        {
                            IngredientId = 23,
                            Category = "Essential Ingredients",
                            Name = "Honey"
                        },
                        new
                        {
                            IngredientId = 24,
                            Category = "Essential Ingredients",
                            Name = "Paprika"
                        },
                        new
                        {
                            IngredientId = 25,
                            Category = "Essential Ingredients",
                            Name = "Vanilla"
                        },
                        new
                        {
                            IngredientId = 26,
                            Category = "Essential Ingredients",
                            Name = "Spaghetti"
                        },
                        new
                        {
                            IngredientId = 27,
                            Category = "Essential Ingredients",
                            Name = "Peanut Butter"
                        },
                        new
                        {
                            IngredientId = 28,
                            Category = "Essential Ingredients",
                            Name = "Chili Powder"
                        },
                        new
                        {
                            IngredientId = 29,
                            Category = "Essential Ingredients",
                            Name = "Cumin"
                        },
                        new
                        {
                            IngredientId = 30,
                            Category = "Essential Ingredients",
                            Name = "Mustard"
                        },
                        new
                        {
                            IngredientId = 31,
                            Category = "Essential Ingredients",
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            IngredientId = 32,
                            Category = "Essential Ingredients",
                            Name = "Cheddar"
                        },
                        new
                        {
                            IngredientId = 33,
                            Category = "Essential Ingredients",
                            Name = "Onion Powder"
                        },
                        new
                        {
                            IngredientId = 34,
                            Category = "Essential Ingredients",
                            Name = "Carrot"
                        },
                        new
                        {
                            IngredientId = 35,
                            Category = "Essential Ingredients",
                            Name = "Tomato"
                        },
                        new
                        {
                            IngredientId = 36,
                            Category = "Essential Ingredients",
                            Name = "Basil"
                        },
                        new
                        {
                            IngredientId = 37,
                            Category = "Essential Ingredients",
                            Name = "Parsley"
                        },
                        new
                        {
                            IngredientId = 38,
                            Category = "Essential Ingredients",
                            Name = "Parmesan"
                        },
                        new
                        {
                            IngredientId = 39,
                            Category = "Essential Ingredients",
                            Name = "Italian Seasoning"
                        },
                        new
                        {
                            IngredientId = 40,
                            Category = "Essential Ingredients",
                            Name = "Thyme"
                        },
                        new
                        {
                            IngredientId = 41,
                            Category = "Essential Ingredients",
                            Name = "Bell Pepper"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
