// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeRedux.Data;

#nullable disable

namespace RecipeRedux.Migrations
{
    [DbContext(typeof(RecipeReduxContext))]
    [Migration("20240416232414_AddedIngredientCategories")]
    partial class AddedIngredientCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecipeRedux.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Essential Ingredients"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Vegetables & Greens"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Dairy & Eggs"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Fruits"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Berries"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Nuts & Seeds"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Cheeses"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Dairy-Free & Meat Substitutes"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Meats"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Poultry"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Fish"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Seafood & Seaweed"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Herbs & Spices"
                        },
                        new
                        {
                            CategoryId = 15,
                            Name = "Sugar & Sweeteners"
                        },
                        new
                        {
                            CategoryId = 16,
                            Name = "Seasonings & Spice Blends"
                        },
                        new
                        {
                            CategoryId = 17,
                            Name = "Baking"
                        },
                        new
                        {
                            CategoryId = 18,
                            Name = "Pre-Made Doughs & Wrappers"
                        },
                        new
                        {
                            CategoryId = 19,
                            Name = "Grains & Cereals"
                        },
                        new
                        {
                            CategoryId = 20,
                            Name = "Legumes"
                        },
                        new
                        {
                            CategoryId = 21,
                            Name = "Pasta"
                        },
                        new
                        {
                            CategoryId = 22,
                            Name = "Bread & Salty Snacks"
                        },
                        new
                        {
                            CategoryId = 23,
                            Name = "Oils & Fats"
                        },
                        new
                        {
                            CategoryId = 24,
                            Name = "Dressings & Vinegars"
                        },
                        new
                        {
                            CategoryId = 25,
                            Name = "Condiments"
                        },
                        new
                        {
                            CategoryId = 26,
                            Name = "Canned Food"
                        },
                        new
                        {
                            CategoryId = 27,
                            Name = "Sauces, Spreads & Dips"
                        },
                        new
                        {
                            CategoryId = 28,
                            Name = "Soups, Stews & Stocks"
                        },
                        new
                        {
                            CategoryId = 29,
                            Name = "Desserts & Sweet Snacks"
                        },
                        new
                        {
                            CategoryId = 30,
                            Name = "Wine, Beer & Spirits"
                        },
                        new
                        {
                            CategoryId = 31,
                            Name = "Beverages"
                        },
                        new
                        {
                            CategoryId = 32,
                            Name = "Supplements & Extracts"
                        });
                });

            modelBuilder.Entity("RecipeRedux.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Salt"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Water"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Butter"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Milk"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Egg"
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "Garlic"
                        },
                        new
                        {
                            IngredientId = 7,
                            Name = "Onion"
                        },
                        new
                        {
                            IngredientId = 8,
                            Name = "Sugar"
                        },
                        new
                        {
                            IngredientId = 9,
                            Name = "Flour"
                        },
                        new
                        {
                            IngredientId = 10,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            IngredientId = 11,
                            Name = "Garlic Powder"
                        },
                        new
                        {
                            IngredientId = 12,
                            Name = "White Rice"
                        },
                        new
                        {
                            IngredientId = 13,
                            Name = "Cinnamon"
                        },
                        new
                        {
                            IngredientId = 14,
                            Name = "Ketchup"
                        },
                        new
                        {
                            IngredientId = 15,
                            Name = "Soy Sauce"
                        },
                        new
                        {
                            IngredientId = 16,
                            Name = "Mayonnaise"
                        },
                        new
                        {
                            IngredientId = 17,
                            Name = "Vegetable Oil"
                        },
                        new
                        {
                            IngredientId = 18,
                            Name = "Bread"
                        },
                        new
                        {
                            IngredientId = 19,
                            Name = "Baking Powder"
                        },
                        new
                        {
                            IngredientId = 20,
                            Name = "Baking Soda"
                        },
                        new
                        {
                            IngredientId = 21,
                            Name = "Oregano"
                        },
                        new
                        {
                            IngredientId = 22,
                            Name = "Potato"
                        },
                        new
                        {
                            IngredientId = 23,
                            Name = "Honey"
                        },
                        new
                        {
                            IngredientId = 24,
                            Name = "Paprika"
                        },
                        new
                        {
                            IngredientId = 25,
                            Name = "Vanilla"
                        },
                        new
                        {
                            IngredientId = 26,
                            Name = "Spaghetti"
                        },
                        new
                        {
                            IngredientId = 27,
                            Name = "Peanut Butter"
                        },
                        new
                        {
                            IngredientId = 28,
                            Name = "Chili Powder"
                        },
                        new
                        {
                            IngredientId = 29,
                            Name = "Cumin"
                        },
                        new
                        {
                            IngredientId = 30,
                            Name = "Mustard"
                        },
                        new
                        {
                            IngredientId = 31,
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            IngredientId = 32,
                            Name = "Cheddar"
                        },
                        new
                        {
                            IngredientId = 33,
                            Name = "Onion Powder"
                        },
                        new
                        {
                            IngredientId = 34,
                            Name = "Carrot"
                        },
                        new
                        {
                            IngredientId = 35,
                            Name = "Tomato"
                        },
                        new
                        {
                            IngredientId = 36,
                            Name = "Basil"
                        },
                        new
                        {
                            IngredientId = 37,
                            Name = "Parsley"
                        },
                        new
                        {
                            IngredientId = 38,
                            Name = "Parmesan"
                        },
                        new
                        {
                            IngredientId = 39,
                            Name = "Italian Seasoning"
                        },
                        new
                        {
                            IngredientId = 40,
                            Name = "Thyme"
                        },
                        new
                        {
                            IngredientId = 41,
                            Name = "Bell Pepper"
                        });
                });

            modelBuilder.Entity("RecipeRedux.Models.IngredientCategory", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("IngredientCategories");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 6,
                            CategoryId = 14
                        },
                        new
                        {
                            IngredientId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 7,
                            CategoryId = 14
                        },
                        new
                        {
                            IngredientId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 8,
                            CategoryId = 15
                        },
                        new
                        {
                            IngredientId = 8,
                            CategoryId = 17
                        },
                        new
                        {
                            IngredientId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 9,
                            CategoryId = 17
                        },
                        new
                        {
                            IngredientId = 9,
                            CategoryId = 19
                        },
                        new
                        {
                            IngredientId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 10,
                            CategoryId = 23
                        },
                        new
                        {
                            IngredientId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 11,
                            CategoryId = 16
                        },
                        new
                        {
                            IngredientId = 12,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 12,
                            CategoryId = 19
                        },
                        new
                        {
                            IngredientId = 13,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 13,
                            CategoryId = 16
                        },
                        new
                        {
                            IngredientId = 14,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 14,
                            CategoryId = 25
                        },
                        new
                        {
                            IngredientId = 15,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 15,
                            CategoryId = 25
                        },
                        new
                        {
                            IngredientId = 16,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 16,
                            CategoryId = 25
                        },
                        new
                        {
                            IngredientId = 17,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 17,
                            CategoryId = 23
                        },
                        new
                        {
                            IngredientId = 18,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 18,
                            CategoryId = 22
                        },
                        new
                        {
                            IngredientId = 19,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 19,
                            CategoryId = 17
                        },
                        new
                        {
                            IngredientId = 20,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 20,
                            CategoryId = 17
                        },
                        new
                        {
                            IngredientId = 21,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 21,
                            CategoryId = 14
                        },
                        new
                        {
                            IngredientId = 22,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 22,
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = 23,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 23,
                            CategoryId = 15
                        },
                        new
                        {
                            IngredientId = 23,
                            CategoryId = 17
                        },
                        new
                        {
                            IngredientId = 24,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 24,
                            CategoryId = 16
                        },
                        new
                        {
                            IngredientId = 25,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 25,
                            CategoryId = 17
                        },
                        new
                        {
                            IngredientId = 25,
                            CategoryId = 29
                        },
                        new
                        {
                            IngredientId = 26,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 26,
                            CategoryId = 21
                        },
                        new
                        {
                            IngredientId = 27,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 27,
                            CategoryId = 7
                        },
                        new
                        {
                            IngredientId = 28,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 28,
                            CategoryId = 16
                        },
                        new
                        {
                            IngredientId = 29,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 29,
                            CategoryId = 16
                        },
                        new
                        {
                            IngredientId = 30,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 30,
                            CategoryId = 25
                        },
                        new
                        {
                            IngredientId = 31,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 31,
                            CategoryId = 10
                        },
                        new
                        {
                            IngredientId = 32,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 32,
                            CategoryId = 8
                        },
                        new
                        {
                            IngredientId = 33,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 33,
                            CategoryId = 16
                        },
                        new
                        {
                            IngredientId = 34,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 34,
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = 35,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 35,
                            CategoryId = 4
                        },
                        new
                        {
                            IngredientId = 36,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 36,
                            CategoryId = 14
                        },
                        new
                        {
                            IngredientId = 37,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 37,
                            CategoryId = 14
                        },
                        new
                        {
                            IngredientId = 38,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 38,
                            CategoryId = 8
                        },
                        new
                        {
                            IngredientId = 39,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 39,
                            CategoryId = 16
                        },
                        new
                        {
                            IngredientId = 40,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 40,
                            CategoryId = 14
                        },
                        new
                        {
                            IngredientId = 41,
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = 41,
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = 41,
                            CategoryId = 14
                        },
                        new
                        {
                            IngredientId = 41,
                            CategoryId = 17
                        });
                });

            modelBuilder.Entity("RecipeRedux.Models.IngredientCategory", b =>
                {
                    b.HasOne("RecipeRedux.Models.Category", "Category")
                        .WithMany("IngredientCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeRedux.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientCategories")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RecipeRedux.Models.Category", b =>
                {
                    b.Navigation("IngredientCategories");
                });

            modelBuilder.Entity("RecipeRedux.Models.Ingredient", b =>
                {
                    b.Navigation("IngredientCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
